### ISSUE TITLE
click pe latest articles sau sidebar

### ISSUE THREAD

**Issue by bogdan-boancas** [tagDiv/td-composer#15]
Cand dai click pe latest articles te duce pe postul pe care dai click in new tab. Nu ar fi ok sa apare setair pt latest articles? Pe sidebar nu stiu sigur cum ar fi dar ii ciudat sa te duca pe post din pagebuilder

**Comment by nicugergely** [comment]
Latest articles va functiona doar din setari, la fel ca si setarile generale ale temei, setarile de meni, footer-ul, etc
