### ISSUE TITLE
eroare block - apare cand dai click pe el

### ISSUE THREAD

**Issue by suport001** [tagDiv/td-composer#55]
![image](https://cloud.githubusercontent.com/assets/6737313/19729158/ac7847bc-9b9e-11e6-9e12-27f842ef968e.png)

**Comment by suport001** [comment]
apare dupa ce stergi un block si dai click sa adaugi altul

**Comment by nicugergely** [comment]
Fixed.

Apare doar la stergea blocului prin butonul din masca, si doar atunci cand nu se da vreun click in alta parte inainte de-a da click pe-un element din sidebar.

Butonul din masca foloseste practic codul de stergere implementat pentru recycle-ul din coltul dreapta jos a ecranului, si dupa operatiunea de stergere ramanea setata variabila tdcOperationUI._currentElementOver
